### ISSUE TITLE
Toast popping up after every few minutes

### ISSUE THREAD

**Issue by AmJay** [afollestad/nock-nock#2]
Toast popping up after every few minutes - "Already checking sites"

Log when toast appears:
08-10 10:13:11.204 18448-18448/com.afollestad.nocknock D/Inquiry: No instances found to destroy by name com.afollestad.nocknock.services.CheckService

**Comment by Jawnnypoo** [comment]
Yeah, this Toast appears every time I launch Pokemon GO for some reason. Quite frustrating!

**Comment by afollestad** [comment]
A temporary workaround would be to clear data for the app, since I haven't reproduced this issue yet.

**Comment by Jawnnypoo** [comment]
Is there a reason for toasting it at all? Just seems like a Service should never really be toasting anything. Maybe a Log.e instead?

**Comment by Jawnnypoo** [comment]
Or surround it with a `if (BuildConfig.DEBUG)`

**Comment by afollestad** [comment]
It's there mainly for debugging purposes. The service should never be started when it's already running if the app is working as intended.

**Comment by Jawnnypoo** [comment]
If it helps with debugging, I have the app installed but I have set up no sites to be checked. Is there a reason to not make this an IntentService instead of a service? That way, you would not have to worry about two of the services running at once since IntentService queues its work and only runs one instance at a time

**Comment by AmJay** [comment]
Yes, clearing app data solved the issue
